U-Wreckcar/U-wreckcar-FE

- app/dashboard/layout.tsx
- app/layout.tsx
- app/page.tsx
- components/header/Header.tsx
- components/sidebar/PlusSideNav.tsx
- components/sidebar/SlimSideNav.tsx
- components/sidebar/styles.module.css
- pages/createutm.tsx
dashboard/layout.tsx 경로를 추가하여 header와 side를 추가하여 layout 컴포넌트를 감싸 header와 side를 보이게 구현했습니다.
> [ADD] layout sidebar, header

- src/components/mainPage/MainBtnTable.tsx
- src/components/mainPage/MainTable.tsx
fix main table onclick event type
> [RELEASE] 서버 배포

- src/app/_app.tsx
- src/app/layout.tsx
- src/app/og-alt.png/page.tsx
- src/app/page.tsx
> [UPDATE] OG IMAGE 3차

- src/components/authes/Kakao.tsx
- src/util/async/axiosConfig.ts
로그인 후 헤더에 직접 쿠키 넣는 함수를 실행시키도록 했습니다.
> [UPDATE] main btn table 쿠키 검사 5차 

- src/components/header/BaseHeader.tsx
헤더에 함수를 넣으니 메인까지 망가져서 제외시켰습니다.
> [UPDATE] login 이후 토큰 undefined 문제 8차

- src/components/header/BaseHeader.tsx
try-catch문을 이용 에러가 났을 때 다시 시도하도록 했습니다.
> [UPDATE] login 이후 토큰 undefined 문제 9차 

- src/components/header/BaseHeader.tsx
> [UPDATE] login 이후 토큰 undefined 문제 10차 

- src/app/layout.tsx
- src/app/og.tsx
> [UPDATE] og 파일 추가

- src/components/header/Header.tsx
> [UPDATE] 헤더가 동시에 나오는 현상 해결

- src/components/mainPage/OutputModal.tsx
- src/util/async/api.ts
> [UPDATE] csv 추가

- src/app/page.tsx
- src/redux/slice/filterSlice.ts
- src/redux/slice/utmSlice.ts
[FIX] redux store 수정으로 인한 에러 페이지 주석
> [FIX] redux store 수정으로 인한 에러 페이지 주석

- src/app/(user)/userinfo/page.tsx
- src/app/(utm)/createutm/page.tsx
- src/shared/modal/Loading.tsx
[🐛[FIX] user 정보 조회가 안되는 현상 해결](https://github.com/U-Wreckcar/U-wreckcar-FE/commit/394362738a912a384d9e97cac6f8480829b4c91c)
> :bug:[FIX] user 정보 조회가 안되는 현상 해결

- src/app/(user)/userinfo/page.tsx
- src/components/mainPage/DeleteModal.tsx
- src/components/mainPage/MainBtnTable.tsx
- src/components/mainPage/MainTable.tsx
> 수정님 체크박스 업데이트 및 서버베포 프로덕션 테스트

- src/app/(user)/userinfo/page.tsx
- src/components/loginPage/LoginBox.module.css
- src/components/loginPage/LoginBox.tsx
- src/shared/modal/Modal.tsx
- src/shared/modal/modal.module.css
✨[ADD] 로그인 페이지 카카오톡 Noti 알럿 추가
> ✨[ADD] 로그인 페이지 카카오톡 Noti 알럿 추가

- src/shared/modal/Modal.tsx
[EDIT] ./modal.module.css 대소문자 수정
> [EDIT] ./modal.module.css 대소문자 수정

- src/app/(user)/signup/page.tsx
- src/app/(user)/userinfo/page.tsx
- src/app/(user)/userinfo/userinfo.module.css
- src/app/(utm)/main/page.tsx
- src/app/page.tsx
- src/components/createPage/CreateUTM.tsx
- src/components/header/RenderHeader.tsx
- src/components/header/styles.module.css
- src/components/loginPage/LocalLogin.tsx
- src/components/loginPage/LoginBox.module.css
- src/components/loginPage/LoginBox.tsx
- src/components/mainPage/MainBtnTable.tsx
- src/components/mainPage/MainTable.tsx
- src/components/mainPage/OutputModal.tsx
- src/components/mainPage/TableData.ts
- src/components/renderModal/RenderModal.tsx
- src/components/renderModal/renderModal.module.css
- src/components/sidebar/SideNav.tsx
- src/components/signUp/SignUp.tsx
- src/components/signUp/signup.module.css
- src/shared/button/Alert.tsx
- src/shared/button/CopyButton.tsx
- src/shared/modal/Modal.tsx
- src/shared/modal/modal.module.css
- src/util/async/api.ts
[UPDATE] 렌더페이지 설문조사 모달 추가 && 로그인페이지 카카오톡 공지 알럿 추가
> [UPDATE] 렌더페이지 설문조사 모달 추가 && 로그인페이지 카카오톡 공지 알럿 추가

- src/app/layout.tsx
- src/components/mainPage/MainBtnTable.tsx
- src/components/mainPage/MainTable.tsx
- src/components/mainPage/ShortenModal.module.css
- src/components/mainPage/ShortenModal.tsx
[[ADD] 메인테이블 숄튼 복사하기 요약보기 상세보기 알럿 추가](https://github.com/U-Wreckcar/U-wreckcar-FE/commit/78ca7b4b5efc2010d0c1f486443cfdc256715b5e)
> [UPDATE] 메인테이블 숄튼 복사하기 요약보기 상세보기 알럿 추가

- src/components/signUp/SignUp.tsx
> :zap: [EDIT] 회원가입 로직 변경

- src/app/globals.css
- src/components/authes/Kakao.tsx
- src/components/header/BaseHeader.tsx
- src/components/loginPage/LocalLogin.tsx
- src/util/async/axiosConfig.ts
로컬로그인할 때 카카오톡 토큰을 백엔드에게 요청을 해서 주석처리하고 테스트
> [UPDATE] 인터셉터 기능 주석처리

- src/app/(user)/userinfo/userinfo.module.css
- src/app/globals.css
- src/components/authes/FindPW.tsx
- src/components/authes/findPW.module.css
- src/components/loginPage/LocalLogin.module.css
- src/components/loginPage/LocalLogin.tsx
- src/components/loginPage/LoginBox.tsx
- src/components/loginPage/LoginModal.tsx
- src/components/loginPage/UserDelModal.tsx
- src/components/loginPage/delModal.module.css
- src/components/loginPage/loginModal.module.css
- src/components/mainPage/main.module.css
- src/components/sidebar/AddUtmModal.module.css
- src/components/signUp/SignUp.tsx
- src/components/signUp/signup.module.css
@new-crystal
[💄[EDIT]회원가입 뷰 완성](https://github.com/U-Wreckcar/U-wreckcar-FE/pull/586/commits/773d7280eb4c0c361389e83f57bf3973594a8091)
[773d728](https://github.com/U-Wreckcar/U-wreckcar-FE/pull/586/commits/773d7280eb4c0c361389e83f57bf3973594a8091)
@new-crystal
[💫[EDIT] detail](https://github.com/U-Wreckcar/U-wreckcar-FE/pull/586/commits/f46331490c8be2a2fa9b9deabde7d91f6c2a0073)
[f463314](https://github.com/U-Wreckcar/U-wreckcar-FE/pull/586/commits/f46331490c8be2a2fa9b9deabde7d91f6c2a0073)
@new-crystal
[💫[EDIT] 비밀번호 찾기 페이지 호버 이벤트](https://github.com/U-Wreckcar/U-wreckcar-FE/pull/586/commits/6ef16ac564867c1d20c1e81c00b379c6d3ee6097)
[6ef16ac](https://github.com/U-Wreckcar/U-wreckcar-FE/pull/586/commits/6ef16ac564867c1d20c1e81c00b379c6d3ee6097)
@new-crystal
[💫[EDIT] 비밀번호 찾기 페이지 호버 …
> 버튼 호버 이벤트/스타일 수정

- src/app/(user)/userinfo/page.tsx
- src/components/authes/FindPW.tsx
- src/components/authes/Kakao.tsx
- src/components/createPage/CreateUTM.module.css
- src/components/createPage/CreateUTM.tsx
- src/components/header/BaseHeader.tsx
- src/components/header/Header.tsx
- src/components/loginPage/LocalLogin.tsx
- src/components/loginPage/UserDelModal.tsx
- src/components/mainPage/MainPage.tsx
- src/components/mainPage/MainTable.tsx
- src/components/mainPage/OutputModal.tsx
- src/components/sidebar/ExcelAddModal.tsx
- src/components/signUp/SignUp.tsx
- src/util/async/api.ts
- src/util/async/axiosConfig.ts
- src/util/async/intercepter.ts
- src/util/importTestCode.tsx
토큰이슈는 
인터셉터 로직을 따로 분리해서 로직을 작성했습니다.
기존에는 함수를 작성해서 호출하는 방식으로 했지만 업데이트 로직은 오브젝트 접근법으로 인터셉터 기능이 작동하도록했습니다.
테스트는 dev, build 환경에서 오류없이 잘 작동하고 토큰 업데이트도 잘 됩니다.
토큰이슈를 해결하면서 비동기 로직에도 에러핸들링과 메인테이블 타입을 다시 정했습니다. 나머지 요청 부분들도 api 파일에서 타입을 정하고 컴포넌트에서 리스폰 받는 형식으로 리팩터링할 예정입니다.
> ♻️ 토큰 이슈 해결 & 비동기로직 에러핸들링 추가 & any 타입 재정의 & 컴포넌트 필요없는 코드 삭제

- readme/css/css.md
- src/app/globals.css
- src/app/layout.tsx
생성하기 페이지에서 리스트를 추가해도 사이드바 하단이 잘리는 현상을 메인레이아웃에 y축 스크롤 주입
> :recycle: main레이아웃 스타일링 추가 && css readme 수정
